version: '3.5'

services:
  postgres:
    image: postgres:bullseye
    container_name: postgres
    restart: always
    # todo: remeve this  (it's for pgAdmin)
    ports:
      - 5432:5432
    environment:
      #! There is a bug when this variable.
      #! Now it's default.
      # - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  frontend:
    image: node:lts-bullseye
    container_name: frontend
    restart: always
    working_dir: /app
    command: bash -c 'yarn && yarn dev'
    env_file:
      - .env
    volumes:
      - ./frontend:/app

  backend:
    image: node:lts-bullseye
    container_name: backend
    restart: always
    working_dir: /app
    # todo: switch this to use yarn insted.
    command: bash -c "npm i && npm run start:dev"
    env_file:
      - .env
    # environment:
      # - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:bullseye
    container_name: nginx
    restart: always
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'
